title: Aaqil Shiraz
logo: /assets/img/Aaqil_Headshot.jpg
description: Certified Tableau Desktop Specialist | Aspiring Data Analyst | Python | SQL
show_downloads: false
theme: jekyll-theme-minimal

# Contact Information
linkedin_username: https://www.linkedin.com/in/aaqilshiraz/
phone_number: "+971544021323"
email: aaqil9365@gmail.com
